Reorganize and extend GCC rule
kuche1/minq-ananicy pull request #20
Opened 2023-10-01 14:50 UTC by diggit

Hi,
Merged `g++` and `gcc` rule file because they are binaries of same compiler and when you have one, you also have the other.
I don't think it make sense to keep them separate. (I'd open issue about this merge first, but this repo has issues disabled :()
Also, what is more important, I extended rule to cover also `cc1plus` (seen when building from AUR) and other binaries.

2023-10-01 14:55 UTC, diggit commented
Also what do you think about extending this by regexp to any gcc toolchain (e.g. also arm-none-eabi-gcc)?

2023-10-03 21:57 UTC, Technetium1 requested changes

2023-10-03 21:57 UTC, Technetium1 commented on ananicy.d/00-default/compilers/gcc.rules
> +{ "name": "collect2",    "type": "compiler" }
Please leave a new line at the end, otherwise perfect!

2023-10-03 22:00 UTC, Technetium1 commented
> Also what do you think about extending this by regexp to any gcc toolchain (e.g. also arm-none-eabi-gcc)?

I think that's valid as well. If you'd like to add the other binaries, please feel free! I don't know that regex is the right way to go about it though.

2023-10-15 13:30 UTC, diggit commented
> > Also what do you think about extending this by regexp to any gcc toolchain (e.g. also arm-none-eabi-gcc)?
> 
> I think that's valid as well. If you'd like to add the other binaries, please feel free! I don't know that regex is the right way to go about it though.

There is a lot combinations of toolchain triples.

ananicy cpp does not support regexes ([yet](https://gitlab.com/ananicy-cpp/ananicy-cpp/-/issues/65)), so it's not relevant at this moment.

2023-10-15 15:45 UTC, Technetium1 approved these changes
Great!

2023-10-15 15:47 UTC, merged